### ISSUE TITLE
Aufbau Produktionsumgebung

### ISSUE THREAD

**Issue by bsantschi** [puzzle/boldideas#1]
- URL: boldideas.puzzle.ch (Produktion)
- Keine Integration
- Sprachen: DE
- Code/Module/Farben/Schriftarten: von Dialog Luzern übernehmen
- Kartenmodul Swisstopo mit Koordinaten Thun
- Footer: Puzzle Logo und auf http://puzzle.ch/decidim verlinken

**Comment by Kagemaru** [comment]
* [X] PROD läuft
* [X] Sprache: DE
* [X] Integrationen sind deaktiviert
* [X] Code Stand ist wie bei Luzern
* [ ] Swisstopo & Karteneinstellungen 
    * [X] Von OIZ übernommen
    * [ ] Muss ich noch testen
    * [ ] Koordinaten von Thun müssen noch eingetragen werden.
* [X] Domains aktiviert
   * [X] https://pitc-stth-boldideas-prod.appuioapp.ch
   * [X] https://boldideas.puzzle.ch
   * [X] https://www.boldideas.puzzle.ch
* [x] Footer einbauen

**Comment by Kagemaru** [comment]
Die Puzzle-Domains sind nun aktiviert und mit Zertifikaten versehen. Die Standarddomain ist: https://boldideas.puzzle.ch
